apiVersion: v1
kind: Secret
metadata:
  name: {{ include "report-app.fullname" . }}-secret
  labels:
    {{- include "report-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.secrets.appKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
